// SPDX-FileCopyrightText: 2026 Sprinkle <40203084+lnn0q@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Shitmed.UserInterface.Systems.PartStatus;
using Content.Shared._Shitmed.Medical.Surgery;
using Content.Shared._Shitmed.Medical.Surgery.Wounds;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Shitmed.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryPartSelector : UIWidget
{
    private readonly Dictionary<TargetBodyPart, TextureButton> _buttons;
    private readonly Dictionary<TargetBodyPart, TextureRect> _textures;
    private readonly PartStatusUIController _controller;
    private Dictionary<TargetBodyPart, SurgeryPartBuiData> _parts = new();
    private TargetBodyPart? _selectedPart;

    public event Action<TargetBodyPart>? OnPartPressed;

    public SurgeryPartSelector()
    {
        RobustXamlLoader.Load(this);
        _controller = UserInterfaceManager.GetUIController<PartStatusUIController>();

        _buttons = new Dictionary<TargetBodyPart, TextureButton>
        {
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Chest, ChestButton },
            { TargetBodyPart.Groin, GroinButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        _textures = new Dictionary<TargetBodyPart, TextureRect>
        {
            { TargetBodyPart.Head, DollHead },
            { TargetBodyPart.Chest, DollTorso },
            { TargetBodyPart.Groin, DollGroin },
            { TargetBodyPart.LeftArm, DollLeftArm },
            { TargetBodyPart.LeftHand, DollLeftHand },
            { TargetBodyPart.RightArm, DollRightArm },
            { TargetBodyPart.RightHand, DollRightHand },
            { TargetBodyPart.LeftLeg, DollLeftLeg },
            { TargetBodyPart.LeftFoot, DollLeftFoot },
            { TargetBodyPart.RightLeg, DollRightLeg },
            { TargetBodyPart.RightFoot, DollRightFoot },
        };

        foreach (var (part, button) in _buttons)
        {
            button.MouseFilter = MouseFilterMode.Stop;
            button.OnPressed += _ => OnPartPressed?.Invoke(part);
            button.OnMouseEntered += _ => SetPartText(part);
            button.OnMouseExited += _ => SetPartText(null);
        }

        SetPartText(null);
    }

    public void SetState(SurgeryBuiState state)
    {
        _parts = state.Parts;

        PatientNameLabel.Text = state.PatientName;
        PatientNameLabel.FontColorOverride = Color.White;
        SpeciesLabel.Text = state.SpeciesName;
        SpeciesLabel.FontColorOverride = Color.LightGray;
        SetPartText(null);

        foreach (var (part, button) in _buttons)
        {
            var visible = _parts.TryGetValue(part, out var data);
            button.Visible = visible;

            if (!_textures.TryGetValue(part, out var texture))
                continue;

            texture.Visible = visible;
            if (!visible || data == null)
            {
                texture.Texture = null;
                continue;
            }

            texture.Texture = _controller.GetTexture(GetStatusSpecifier(part, data.Severity));
        }

        SetSelected(_selectedPart);
    }

    public void SetSelected(TargetBodyPart? part)
    {
        if (part != null && !_parts.ContainsKey(part.Value))
            part = null;

        _selectedPart = part;

        foreach (var (buttonPart, button) in _buttons)
            button.Modulate = buttonPart == part
                ? Color.Cyan.WithAlpha(0.35f)
                : Color.White;
    }

    private void SetPartText(TargetBodyPart? part)
    {
        PartNameLabel.Text = part != null && _parts.TryGetValue(part.Value, out var data)
            ? data.Name
            : "-";
        PartNameLabel.FontColorOverride = Color.LightGray;
    }

    private static SpriteSpecifier.Rsi GetStatusSpecifier(TargetBodyPart part, WoundableSeverity severity)
    {
        var partName = part.ToString().ToLowerInvariant();
        return new SpriteSpecifier.Rsi(new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{partName}.rsi"), $"{partName}_{(int) severity}");
    }
}
