- type: body
  id: Protogen
  name: protogen # Starlight, quotation marks removed
  root: chest
  slots:
    head:
      part: HeadProtogen
      connections:
      - chest
      organs:
        brain: OrganProtogenBrain
        eyes: OrganProtogenEyes
        tongue: OrganProtogenTongue
    chest:
      part: TorsoProtogen
      connections:
      - right arm
      - left arm
      - head
      - groin
      organs:
        heart: OrganProtogenHeart
        lungs: OrganProtogenLungs
    groin:
      part: GroinProtogen
      connections:
      - right leg
      - left leg
      organs:
        stomach: OrganProtogenStomach
        liver: OrganProtogenLiver
        kidneys: OrganProtogenKidneys
    right arm:
      part: RightArmProtogen
      connections:
      - right hand
    left arm:
      part: LeftArmProtogen
      connections:
      - left hand
    right hand:
      part: RightHandProtogen
    left hand:
      part: LeftHandProtogen
    right leg:
      part: RightLegProtogen
      connections:
      - right foot
    left leg:
      part: LeftLegProtogen
      connections:
      - left foot
    right foot:
      part: RightFootProtogen
    left foot:
      part: LeftFootProtogen
