- type: entity
  name: dueling rapier
  parent: [ BaseSword, BaseGrandTheftContraband ]
  id: DuelingRapier
  description: A thin, elegant sword made for lunging over banana peels.
  components:
  - type: Sprite
    sprite: _Omu/Objects/Weapons/Melee/wardenrapier.rsi
  - type: MeleeWeapon
    angle: 0
    animationRotation: -90
    wideAnimationRotation: -90
    heavyStaminaCost: 10 #ratbite
    damage:
      types:
        Piercing: 20 # slightly more than the captain sabre but with less attack speed, idk how high this should really be
    soundHit:
        path: /Audio/Weapons/bladeslice.ogg
  - type: Item
    shape:
    - 0,0,0,3
    storedRotation: -45
  - type: MeleeDash
    emoteOnDash: null
    length: 2
    canDashWhileWeightless: false # Omu
  - type: UseDelay
    delay: 5 # ratbite
  - type: Tag
    tags:
    - DuelingRapier
  - type: StealTarget
    stealGroup: WeaponEnergyShotgun
  - type: DisarmMalus
  - type: Reflect
    reflectProb: 0.3
    spread: 30
