using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client._BRatbite.UserInterface.Systems.Ghost;

[GenerateTypedNameReferences]
public sealed partial class AltServerConfirmWindow : DefaultWindow
{
    public event Action? OnConfirmPressed;

    public AltServerConfirmWindow()
    {
        RobustXamlLoader.Load(this);
        ConfirmButton.OnPressed += _ => OnConfirmPressed?.Invoke();
    }
}
